name: Auth

on:
  push:

jobs:
  Auth:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Auth
        run: bash ./scripts/auth.sh dev