name: Promotion

on:
    workflow_run:
        workflows: ["Deploy"]
        types:
            - completed

jobs:
<<<<<<< feature/temp3
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Determine Promotion Path
        env:
          SOURCE_BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: bash ./scripts/promotion.sh
=======
    promote:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - run: echo "Create next PR"
>>>>>>> dev
